// ==================== DATA MODELS ====================
class Course {
  final String id;
  final String title;
  final String slug;
  final String description;
  final String emoji;
  final int studentCount;
  final int color;
  final String category;
  final List<String> topics;
  final String duration;
  final String level;
  final double rating;

  const Course({
    required this.id,
    required this.title,    required this.slug,
    required this.description,
    required this.emoji,
    required this.studentCount,
    required this.color,
    required this.category,
    required this.topics,
    required this.duration,
    required this.level,
    this.rating = 4.8,
  });

  /// ✅ ADD THIS METHOD
  factory Course.fromJson(Map<String, dynamic> json) {
    return Course(
      id: json['id'] ?? '',
      title: json['title'] ?? '',
      slug: json['slug'] ?? '',
      description: json['description'] ?? '',
      emoji: json['emoji'] ?? '📘',

      /// 🔥 Important conversions
      studentCount: (json['studentCount'] ?? 0) as int,

      /// If color comes like "0xff1e40af" (string), convert it
      color: json['color'] is String
          ? int.parse(json['color'])
          : (json['color'] ?? 0),

      category: json['category'] ?? '',

      /// Convert dynamic list → List<String>
      topics: (json['topics'] as List?)
              ?.map((e) => e.toString())
              .toList() ??
          [],

      duration: json['duration'] ?? '',
      level: json['level'] ?? '',

      /// Ensure double
      rating: (json['rating'] ?? 4.8).toDouble(),
    );
  }
}
// class Course {
//   final String id;
//   final String title;
//   final String description;
//   final String emoji;
//   final int studentCount;
//   final int color;
//   final String category;
//   final List<String> topics;
//   final String duration;
//   final String level;
//   final double rating;

//   const Course({
//     required this.id,
//     required this.title,
//     required this.description,
//     required this.emoji,
//     required this.studentCount,
//     required this.color,
//     required this.category,
//     required this.topics,
//     required this.duration,
//     required this.level,
//     this.rating = 4.8,
//   });
// }

// ==================== COURSE DATA ====================
const List<Course> allCourses = [
  Course(
    id: "f1",
    title: "HTML & CSS Fundamentals",
    description: "Master the building blocks of the web",
    emoji: "🌐",
    studentCount: 12500,
    color: 0xff1e40af,
    category: "Frontend",
    topics: ["HTML5 Semantic", "CSS Selectors", "Box Model", "Flexbox", "Grid"],
    duration: "8 hours",
    level: "Beginner",
    slug: "html",
  ),
  Course(
    id: "f2",
    title: "JavaScript Mastery",
    description: "Modern JavaScript from scratch",
    emoji: "📜",
    studentCount: 15200,
    color: 0xff1e40af,
    category: "Frontend",
    topics: ["ES6+", "Async/Await", "DOM", "API Calls", "Promises"],
    duration: "12 hours",
    level: "Beginner",
    slug: "javascript",
  ),
  Course(
    id: "f3",
    title: "React Complete Guide",
    description: "Build modern UIs with React",
    emoji: "⚛️",
    studentCount: 18300,
    color: 0xff1e40af,
    category: "Frontend",
    topics: ["Hooks", "Context", "Redux", "Next.js", "Performance"],
    duration: "16 hours",
    level: "Intermediate",
    slug: "reactjs",
  ),
  Course(
    id: "f4",
    title: "TypeScript Pro",
    description: "Type-safe JavaScript development",
    emoji: "📘",
    studentCount: 7200,
    color: 0xff1e40af,
    category: "Frontend",
    topics: ["Types", "Interfaces", "Generics", "Decorators", "Advanced Types"],
    duration: "10 hours",
    level: "Intermediate",
    slug: "typescript",
  ),
  // Course(
  //   id: "f5",
  //   title: "Tailwind CSS Mastery",
  //   description: "Utility-first CSS framework",
  //   emoji: "🎨",
  //   studentCount: 11200,
  //   color: 0xff1e40af,
  //   category: "Frontend",
  //   topics: [
  //     "Responsive",
  //     "Dark Mode",
  //     "Custom Config",
  //     "Animations",
  //     "Plugins",
  //   ],
  //   duration: "6 hours",
  //   level: "Beginner",
  // ),
  // Course(
  //   id: "f6",
  //   title: "Angular Complete Guide",
  //   description: "Build enterprise Angular apps",
  //   emoji: "🅰️",
  //   studentCount: 9800,
  //   color: 0xff1e40af,
  //   category: "Frontend",
  //   topics: ["Components", "RxJS", "Routing", "Forms", "NgRx"],
  //   duration: "14 hours",
  //   level: "Intermediate",
  // ),
  // Course(
  //   id: "f7",
  //   title: "Vue.js Mastery",
  //   description: "Progressive JS framework",
  //   emoji: "🟩",
  //   studentCount: 8700,
  //   color: 0xff1e40af,
  //   category: "Frontend",
  //   topics: ["Vue3", "Composition API", "Pinia", "Routing", "SSR"],
  //   duration: "10 hours",
  //   level: "Intermediate",
  // ),
//   Course(
//     id: "f8",
//     title: "Web Performance Optimization",
//     description: "Speed up your web apps",
//     emoji: "⚡",
//     studentCount: 6500,
//     color: 0xff1e40af,
//     category: "Frontend",
//     topics: ["Lazy Load", "Caching", "Lighthouse", "Bundle Size", "CDN"],
//     duration: "6 hours",
//     level: "Advanced",
//   ),
//   Course(
//     id: "b1",
//     title: "Node.js & Express",
//     description: "JavaScript backend development",
//     emoji: "🟢",
//     studentCount: 14200,
//     color: 0xff047857,
//     category: "Backend",
//     topics: ["REST APIs", "Middleware", "Auth", "MongoDB", "PostgreSQL"],
//     duration: "14 hours",
//     level: "Beginner",
//   ),
//   Course(
//     id: "b2",
//     title: "Python Backend",
//     description: "Django & Flask mastery",
//     emoji: "🐍",
//     studentCount: 13500,
//     color: 0xff047857,
//     category: "Backend",
//     topics: ["Django", "Flask", "APIs", "Deployment", "Testing"],
//     duration: "16 hours",
//     level: "Beginner",
//   ),
//   Course(
//     id: "b3",
//     title: "GraphQL API Design",
//     description: "Modern API development",
//     emoji: "📊",
//     studentCount: 7500,
//     color: 0xff047857,
//     category: "Backend",
//     topics: ["Queries", "Mutations", "Subscriptions", "Apollo", "Caching"],
//     duration: "10 hours",
//     level: "Intermediate",
//   ),
//   Course(
//     id: "b4",
//     title: "Java Spring Boot",
//     description: "Enterprise backend development",
//     emoji: "☕",
//     studentCount: 14200,
//     color: 0xff047857,
//     category: "Backend",
//     topics: ["Spring", "REST", "Security", "JPA", "Microservices"],
//     duration: "18 hours",
//     level: "Intermediate",
//   ),
//   Course(
//     id: "b5",
//     title: "Go Backend Development",
//     description: "High-performance APIs with Go",
//     emoji: "🐹",
//     studentCount: 7200,
//     color: 0xff047857,
//     category: "Backend",
//     topics: ["Gin", "Concurrency", "REST", "gRPC", "Performance"],
//     duration: "12 hours",
//     level: "Intermediate",
//   ),
//   Course(
//     id: "b6",
//     title: "Microservices Architecture",
//     description: "Build scalable systems",
//     emoji: "🧩",
//     studentCount: 8100,
//     color: 0xff047857,
//     category: "Backend",
//     topics: ["Service Mesh", "Kafka", "API Gateway", "Scaling", "Resilience"],
//     duration: "16 hours",
//     level: "Advanced",
//   ),
//   Course(
//     id: "d1",
//     title: "Docker & Kubernetes",
//     description: "Container orchestration",
//     emoji: "🐳",
//     studentCount: 13200,
//     color: 0xff6b21a8,
//     category: "DevOps",
//     topics: ["Docker", "K8s", "Helm", "CI/CD", "Monitoring"],
//     duration: "14 hours",
//     level: "Intermediate",
//   ),
//   Course(
//     id: "d2",
//     title: "CI/CD Pipelines",
//     description: "GitHub Actions & Jenkins",
//     emoji: "⚙️",
//     studentCount: 8900,
//     color: 0xff6b21a8,
//     category: "DevOps",
//     topics: ["GitHub Actions", "Jenkins", "Automation", "Testing", "Security"],
//     duration: "10 hours",
//     level: "Intermediate",
//   ),
//   Course(
//     id: "d3",
//     title: "Terraform Essentials",
//     description: "Infrastructure as Code",
//     emoji: "🏗️",
//     studentCount: 7600,
//     color: 0xff6b21a8,
//     category: "DevOps",
//     topics: ["IaC", "AWS", "Provisioning", "State", "Modules"],
//     duration: "10 hours",
//     level: "Intermediate",
//   ),
//   Course(
//     id: "d4",
//     title: "Monitoring with Prometheus",
//     description: "System monitoring and alerts",
//     emoji: "📈",
//     studentCount: 5200,
//     color: 0xff6b21a8,
//     category: "DevOps",
//     topics: ["Metrics", "Grafana", "Alerts", "Dashboards", "Logs"],
//     duration: "8 hours",
//     level: "Intermediate",
//   ),
//   Course(
//     id: "d5",
//     title: "Linux for DevOps",
//     description: "Master Linux commands",
//     emoji: "🐧",
//     studentCount: 11300,
//     color: 0xff6b21a8,
//     category: "DevOps",
//     topics: ["Shell", "Permissions", "Networking", "Processes", "Automation"],
//     duration: "10 hours",
//     level: "Beginner",
//   ),
//   Course(
//     id: "a1",
//     title: "Machine Learning Basics",
//     description: "Core ML concepts",
//     emoji: "🤖",
//     studentCount: 11200,
//     color: 0xff9f1239,
//     category: "AI & ML",
//     topics: [
//       "Regression",
//       "Classification",
//       "Clustering",
//       "Evaluation",
//       "Feature Engineering",
//     ],
//     duration: "12 hours",
//     level: "Beginner",
//   ),
//   Course(
//     id: "a2",
//     title: "Deep Learning",
//     description: "Neural networks with TensorFlow",
//     emoji: "🧠",
//     studentCount: 10500,
//     color: 0xff9f1239,
//     category: "AI & ML",
//     topics: ["CNN", "RNN", "Transformers", "GANs", "Attention"],
//     duration: "16 hours",
//     level: "Advanced",
//   ),
//   Course(
//     id: "a3",
//     title: "NLP with Python",
//     description: "Text processing and transformers",
//     emoji: "📝",
//     studentCount: 8400,
//     color: 0xff9f1239,
//     category: "AI & ML",
//     topics: ["NLP", "BERT", "Tokenization", "Embeddings", "Transformers"],
//     duration: "14 hours",
//     level: "Intermediate",
//   ),
//   Course(
//     id: "a4",
//     title: "Computer Vision",
//     description: "Image processing with OpenCV",
//     emoji: "📷",
//     studentCount: 7600,
//     color: 0xff9f1239,
//     category: "AI & ML",
//     topics: ["OpenCV", "CNN", "Detection", "Segmentation", "YOLO"],
//     duration: "12 hours",
//     level: "Intermediate",
//   ),
//   Course(
//     id: "a5",
//     title: "Generative AI",
//     description: "Build AI apps with LLMs",
//     emoji: "✨",
//     studentCount: 15000,
//     color: 0xff9f1239,
//     category: "AI & ML",
//     topics: ["GPT", "Prompting", "LangChain", "RAG", "Fine-tuning"],
//     duration: "10 hours",
//     level: "Beginner",
//   ),
//   Course(
//     id: "m1",
//     title: "Flutter Complete",
//     description: "Cross-platform mobile apps",
//     emoji: "🦋",
//     studentCount: 15800,
//     color: 0xff0369a1,
//     category: "Mobile",
//     topics: ["Widgets", "State", "Animations", "Firebase", "Testing"],
//     duration: "16 hours",
//     level: "Beginner",
//   ),
//   Course(
//     id: "m2",
//     title: "React Native",
//     description: "Build native apps with React",
//     emoji: "⚛️",
//     studentCount: 12400,
//     color: 0xff0369a1,
//     category: "Mobile",
//     topics: [
//       "Components",
//       "Navigation",
//       "Native Modules",
//       "Deployment",
//       "Performance",
//     ],
//     duration: "14 hours",
//     level: "Intermediate",
//   ),
//   Course(
//     id: "m3",
//     title: "Android Kotlin",
//     description: "Native Android development",
//     emoji: "🤖",
//     studentCount: 9800,
//     color: 0xff0369a1,
//     category: "Mobile",
//     topics: ["Kotlin", "Jetpack", "Compose", "Navigation", "Room"],
//     duration: "14 hours",
//     level: "Intermediate",
//   ),
//   Course(
//     id: "m4",
//     title: "iOS Swift",
//     description: "Build iOS apps",
//     emoji: "🍎",
//     studentCount: 8700,
//     color: 0xff0369a1,
//     category: "Mobile",
//     topics: ["SwiftUI", "UIKit", "Networking", "CoreData", "Animations"],
//     duration: "14 hours",
//     level: "Intermediate",
//   ),
//   Course(
//     id: "m5",
//     title: "Flutter Advanced",
//     description: "Production-ready Flutter apps",
//     emoji: "🔥",
//     studentCount: 9200,
//     color: 0xff0369a1,
//     category: "Mobile",
//     topics: ["Architecture", "Riverpod", "Animations", "Performance", "CI/CD"],
//     duration: "12 hours",
//     level: "Advanced",
//   ),
//   Course(
//     id: "c1",
//     title: "AWS Fundamentals",
//     description: "Core AWS services and architecture",
//     emoji: "☁️",
//     studentCount: 18500,
//     color: 0xff1d4ed8,
//     category: "Cloud",
//     topics: ["EC2", "S3", "IAM", "VPC", "CloudWatch"],
//     duration: "12 hours",
//     level: "Beginner",
//   ),
//   Course(
//     id: "c2",
//     title: "Azure Cloud Essentials",
//     description: "Microsoft Azure core services",
//     emoji: "🔷",
//     studentCount: 12400,
//     color: 0xff1d4ed8,
//     category: "Cloud",
//     topics: ["VM", "Blob Storage", "Azure AD", "Networking", "Monitoring"],
//     duration: "10 hours",
//     level: "Beginner",
//   ),
//   Course(
//     id: "c3",
//     title: "Google Cloud Platform (GCP)",
//     description: "GCP services and deployment",
//     emoji: "🌐",
//     studentCount: 9800,
//     color: 0xff1d4ed8,
//     category: "Cloud",
//     topics: [
//       "Compute Engine",
//       "Cloud Storage",
//       "BigQuery",
//       "IAM",
//       "Kubernetes",
//     ],
//     duration: "12 hours",
//     level: "Intermediate",
//   ),
//   Course(
//     id: "c4",
//     title: "Cloud Architecture & Design",
//     description: "Design scalable cloud systems",
//     emoji: "🏗️",
//     studentCount: 8600,
//     color: 0xff1d4ed8,
//     category: "Cloud",
//     topics: [
//       "Scalability",
//       "Load Balancing",
//       "High Availability",
//       "Cost Optimization",
//       "Security",
//     ],
//     duration: "14 hours",
//     level: "Advanced",
//   ),
//   Course(
//     id: "c5",
//     title: "Serverless Architecture",
//     description: "Build apps without servers",
//     emoji: "⚡",
//     studentCount: 7900,
//     color: 0xff1d4ed8,
//     category: "Cloud",
//     topics: [
//       "AWS Lambda",
//       "API Gateway",
//       "Firebase",
//       "Event-driven",
//       "Scaling",
//     ],
//     duration: "8 hours",
//     level: "Intermediate",
//   ),
//   Course(
//     id: "c6",
//     title: "Cloud Security",
//     description: "Secure cloud infrastructure",
//     emoji: "🔐",
//     studentCount: 7200,
//     color: 0xff1d4ed8,
//     category: "Cloud",
//     topics: [
//       "IAM",
//       "Encryption",
//       "Zero Trust",
//       "Compliance",
//       "Threat Detection",
//     ],
//     duration: "10 hours",
//     level: "Intermediate",
//   ),
//   Course(
//   id: "db1",
//   title: "SQL Fundamentals",
//   description: "Learn relational databases from scratch",
//   emoji: "🗃️",
//   studentCount: 21000,
//   color: 0xff065f46,
//   category: "Database",
//   topics: ["SELECT", "JOIN", "Indexes", "Normalization", "Transactions"],
//   duration: "10 hours",
//   level: "Beginner",
// ),
// Course(
//   id: "db2",
//   title: "Advanced SQL & Optimization",
//   description: "Write high-performance queries",
//   emoji: "⚡",
//   studentCount: 13200,
//   color: 0xff065f46,
//   category: "Database",
//   topics: ["Query Plans", "Indexes", "Optimization", "Partitioning", "Tuning"],
//   duration: "12 hours",
//   level: "Intermediate",
// ),
// Course(
//   id: "db3",
//   title: "MongoDB Complete Guide",
//   description: "NoSQL database mastery",
//   emoji: "🍃",
//   studentCount: 14500,
//   color: 0xff065f46,
//   category: "Database",
//   topics: ["Documents", "Aggregation", "Indexing", "Replication", "Sharding"],
//   duration: "12 hours",
//   level: "Beginner",
// ),
// Course(
//   id: "db4",
//   title: "PostgreSQL Deep Dive",
//   description: "Advanced relational database",
//   emoji: "🐘",
//   studentCount: 9800,
//   color: 0xff065f46,
//   category: "Database",
//   topics: ["Functions", "Triggers", "Indexes", "JSONB", "Performance"],
//   duration: "14 hours",
//   level: "Intermediate",
// ),
// Course(
//   id: "db5",
//   title: "Redis & Caching",
//   description: "In-memory data storage",
//   emoji: "🔥",
//   studentCount: 8700,
//   color: 0xff065f46,
//   category: "Database",
//   topics: ["Caching", "Pub/Sub", "TTL", "Performance", "Distributed Cache"],
//   duration: "8 hours",
//   level: "Intermediate",
// ),
// Course(
//   id: "db6",
//   title: "Database Design & Architecture",
//   description: "Design scalable database systems",
//   emoji: "🏗️",
//   studentCount: 7600,
//   color: 0xff065f46,
//   category: "Database",
//   topics: ["ER Modeling", "Normalization", "Sharding", "Replication", "Scaling"],
//   duration: "12 hours",
//   level: "Advanced",
// ),
// Course(
//   id: "t1",
//   title: "Software Testing Fundamentals",
//   description: "Basics of manual and automated testing",
//   emoji: "🧪",
//   studentCount: 17500,
//   color: 0xffb45309,
//   category: "Testing",
//   topics: ["SDLC", "STLC", "Test Cases", "Bug Lifecycle", "Agile Testing"],
//   duration: "8 hours",
//   level: "Beginner",
// ),
// Course(
//   id: "t2",
//   title: "Automation Testing with Selenium",
//   description: "Web automation using Selenium",
//   emoji: "🤖",
//   studentCount: 14200,
//   color: 0xffb45309,
//   category: "Testing",
//   topics: ["Selenium", "WebDriver", "TestNG", "Locators", "Framework"],
//   duration: "12 hours",
//   level: "Intermediate",
// ),
// Course(
//   id: "t3",
//   title: "API Testing with Postman",
//   description: "Test REST APIs efficiently",
//   emoji: "📡",
//   studentCount: 12100,
//   color: 0xffb45309,
//   category: "Testing",
//   topics: ["REST API", "Postman", "Collections", "Assertions", "Automation"],
//   duration: "6 hours",
//   level: "Beginner",
// ),
// Course(
//   id: "t4",
//   title: "Performance Testing",
//   description: "Load and stress testing apps",
//   emoji: "⚡",
//   studentCount: 9800,
//   color: 0xffb45309,
//   category: "Testing",
//   topics: ["JMeter", "Load Testing", "Stress Testing", "Monitoring", "Reports"],
//   duration: "10 hours",
//   level: "Intermediate",
// ),
// Course(
//   id: "t5",
//   title: "Unit Testing & TDD",
//   description: "Write testable code",
//   emoji: "🧩",
//   studentCount: 8700,
//   color: 0xffb45309,
//   category: "Testing",
//   topics: ["Unit Tests", "Mocking", "TDD", "Coverage", "Best Practices"],
//   duration: "8 hours",
//   level: "Intermediate",
// ),
// Course(
//   id: "t6",
//   title: "Mobile App Testing",
//   description: "Test Android & iOS apps",
//   emoji: "📱",
//   studentCount: 7600,
//   color: 0xffb45309,
//   category: "Testing",
//   topics: ["Appium", "UI Testing", "Device Testing", "Automation", "CI/CD"],
//   duration: "10 hours",
//   level: "Intermediate",
// ),
// Course(
//   id: "s1",
//   title: "Cyber Security Fundamentals",
//   description: "Introduction to security concepts",
//   emoji: "🛡️",
//   studentCount: 16800,
//   color: 0xff991b1b,
//   category: "Cyber Security",
//   topics: ["CIA Triad", "Threats", "Vulnerabilities", "Risk", "Security Basics"],
//   duration: "8 hours",
//   level: "Beginner",
// ),
// Course(
//   id: "s2",
//   title: "Ethical Hacking",
//   description: "Learn penetration testing",
//   emoji: "💻",
//   studentCount: 15200,
//   color: 0xff991b1b,
//   category: "Cyber Security",
//   topics: ["Recon", "Scanning", "Exploitation", "Tools", "Kali Linux"],
//   duration: "14 hours",
//   level: "Intermediate",
// ),
// Course(
//   id: "s3",
//   title: "Web Security",
//   description: "Secure web applications",
//   emoji: "🌐",
//   studentCount: 12400,
//   color: 0xff991b1b,
//   category: "Cyber Security",
//   topics: ["OWASP Top 10", "XSS", "SQL Injection", "CSRF", "Auth"],
//   duration: "10 hours",
//   level: "Intermediate",
// ),
// Course(
//   id: "s4",
//   title: "Network Security",
//   description: "Protect networks and systems",
//   emoji: "📡",
//   studentCount: 9800,
//   color: 0xff991b1b,
//   category: "Cyber Security",
//   topics: ["Firewalls", "IDS/IPS", "VPN", "Protocols", "Monitoring"],
//   duration: "12 hours",
//   level: "Intermediate",
// ),
// Course(
//   id: "s5",
//   title: "Cloud Security",
//   description: "Secure cloud infrastructure",
//   emoji: "☁️",
//   studentCount: 8700,
//   color: 0xff991b1b,
//   category: "Cyber Security",
//   topics: ["IAM", "Encryption", "Zero Trust", "Compliance", "Monitoring"],
//   duration: "10 hours",
//   level: "Intermediate",
// ),
// Course(
//   id: "s6",
//   title: "Security Operations (SOC)",
//   description: "Threat detection and response",
//   emoji: "🚨",
//   studentCount: 7600,
//   color: 0xff991b1b,
//   category: "Cyber Security",
//   topics: ["SIEM", "Incident Response", "Threat Hunting", "Logs", "Forensics"],
//   duration: "12 hours",
//   level: "Advanced",
// ),
// Course(
//   id: "u1",
//   title: "UI/UX Fundamentals",
//   description: "Basics of user interface and experience design",
//   emoji: "🎨",
//   studentCount: 14200,
//   color: 0xffbe185d,
//   category: "UI/UX",
//   topics: ["Design Principles", "Color Theory", "Typography", "Layout", "Accessibility"],
//   duration: "8 hours",
//   level: "Beginner",
// ),
// Course(
//   id: "u2",
//   title: "Figma Mastery",
//   description: "Design modern UI with Figma",
//   emoji: "🧩",
//   studentCount: 16800,
//   color: 0xffbe185d,
//   category: "UI/UX",
//   topics: ["Components", "Auto Layout", "Prototyping", "Design Systems", "Plugins"],
//   duration: "10 hours",
//   level: "Beginner",
// ),
// Course(
//   id: "u3",
//   title: "User Experience (UX) Research",
//   description: "Understand user behavior",
//   emoji: "🔍",
//   studentCount: 9200,
//   color: 0xffbe185d,
//   category: "UI/UX",
//   topics: ["User Research", "Personas", "Journey Mapping", "Usability Testing", "Insights"],
//   duration: "8 hours",
//   level: "Intermediate",
// ),
// Course(
//   id: "u4",
//   title: "Wireframing & Prototyping",
//   description: "Design app flows and interactions",
//   emoji: "📐",
//   studentCount: 8700,
//   color: 0xffbe185d,
//   category: "UI/UX",
//   topics: ["Wireframes", "Low/High Fidelity", "Prototypes", "User Flows", "Testing"],
//   duration: "8 hours",
//   level: "Beginner",
// ),
// Course(
//   id: "u5",
//   title: "Design Systems & UI Architecture",
//   description: "Build scalable design systems",
//   emoji: "🏗️",
//   studentCount: 7800,
//   color: 0xffbe185d,
//   category: "UI/UX",
//   topics: ["Components", "Tokens", "Consistency", "Scalability", "Guidelines"],
//   duration: "10 hours",
//   level: "Advanced",
// ),
// Course(
//   id: "u6",
//   title: "Mobile App UI Design",
//   description: "Design modern mobile interfaces",
//   emoji: "📱",
//   studentCount: 9600,
//   color: 0xffbe185d,
//   category: "UI/UX",
//   topics: ["iOS Design", "Material UI", "Responsiveness", "Animations", "UX Patterns"],
//   duration: "9 hours",
//   level: "Intermediate",
// ),
// Course(
//   id: "sd1",
//   title: "System Design Fundamentals",
//   description: "Basics of scalable system design",
//   emoji: "🏗️",
//   studentCount: 18500,
//   color: 0xff4338ca,
//   category: "System Design",
//   topics: ["Scalability", "Latency", "Throughput", "CAP Theorem", "Load Balancing"],
//   duration: "10 hours",
//   level: "Beginner",
// ),
// Course(
//   id: "sd2",
//   title: "High-Level Design (HLD)",
//   description: "Design large-scale architectures",
//   emoji: "📐",
//   studentCount: 14200,
//   color: 0xff4338ca,
//   category: "System Design",
//   topics: ["Microservices", "Monolith", "APIs", "Architecture Patterns", "Trade-offs"],
//   duration: "12 hours",
//   level: "Intermediate",
// ),
// Course(
//   id: "sd3",
//   title: "Low-Level Design (LLD)",
//   description: "Detailed system component design",
//   emoji: "🧩",
//   studentCount: 12100,
//   color: 0xff4338ca,
//   category: "System Design",
//   topics: ["OOP", "Design Patterns", "SOLID", "Class Design", "UML"],
//   duration: "10 hours",
//   level: "Intermediate",
// ),
// Course(
//   id: "sd4",
//   title: "Scalable Microservices Architecture",
//   description: "Build distributed systems",
//   emoji: "⚙️",
//   studentCount: 9800,
//   color: 0xff4338ca,
//   category: "System Design",
//   topics: ["Service Mesh", "API Gateway", "Event-driven", "Kafka", "Resilience"],
//   duration: "14 hours",
//   level: "Advanced",
// ),
// Course(
//   id: "sd5",
//   title: "Designing Real-Time Systems",
//   description: "Build chat, streaming, real-time apps",
//   emoji: "⚡",
//   studentCount: 8700,
//   color: 0xff4338ca,
//   category: "System Design",
//   topics: ["WebSockets", "Streaming", "Queues", "Scaling", "Consistency"],
//   duration: "12 hours",
//   level: "Advanced",
// ),
// Course(
//   id: "sd6",
//   title: "System Design Interview Prep",
//   description: "Crack system design interviews",
//   emoji: "🎯",
//   studentCount: 16500,
//   color: 0xff4338ca,
//   category: "System Design",
//   topics: ["Case Studies", "Trade-offs", "Patterns", "Mock Interviews", "Best Practices"],
//   duration: "10 hours",
//   level: "Intermediate",
// ),
// Course(
//   id: "tl1",
//   title: "Git & GitHub Mastery",
//   description: "Version control and collaboration",
//   emoji: "🔧",
//   studentCount: 22000,
//   color: 0xff475569,
//   category: "Tools",
//   topics: ["Git Basics", "Branches", "Merging", "Pull Requests", "Workflows"],
//   duration: "8 hours",
//   level: "Beginner",
// ),
// Course(
//   id: "tl2",
//   title: "VS Code Productivity",
//   description: "Boost coding efficiency",
//   emoji: "💻",
//   studentCount: 14500,
//   color: 0xff475569,
//   category: "Tools",
//   topics: ["Extensions", "Shortcuts", "Debugging", "Customization", "Snippets"],
//   duration: "6 hours",
//   level: "Beginner",
// ),
// Course(
//   id: "tl3",
//   title: "Postman API Testing Tool",
//   description: "Master API testing workflow",
//   emoji: "📡",
//   studentCount: 13200,
//   color: 0xff475569,
//   category: "Tools",
//   topics: ["Requests", "Collections", "Environments", "Automation", "Mock APIs"],
//   duration: "6 hours",
//   level: "Beginner",
// ),
// Course(
//   id: "tl4",
//   title: "Docker for Developers",
//   description: "Containerization for apps",
//   emoji: "🐳",
//   studentCount: 16800,
//   color: 0xff475569,
//   category: "Tools",
//   topics: ["Containers", "Images", "Dockerfile", "Compose", "Deployment"],
//   duration: "10 hours",
//   level: "Intermediate",
// ),
// Course(
//   id: "tl5",
//   title: "Linux Command Line",
//   description: "Master terminal productivity",
//   emoji: "🐧",
//   studentCount: 15800,
//   color: 0xff475569,
//   category: "Tools",
//   topics: ["Shell", "File System", "Permissions", "Networking", "Automation"],
//   duration: "8 hours",
//   level: "Beginner",
// ),
// Course(
//   id: "tl6",
//   title: "Jira & Agile Tools",
//   description: "Project management tools",
//   emoji: "📋",
//   studentCount: 9800,
//   color: 0xff475569,
//   category: "Tools",
//   topics: ["Jira", "Scrum", "Kanban", "Sprint Planning", "Tracking"],
//   duration: "6 hours",
//   level: "Beginner",
// ),Course(
//   id: "ip1",
//   title: "DSA for Interviews",
//   description: "Master data structures & algorithms",
//   emoji: "📊",
//   studentCount: 25000,
//   color: 0xff0ea5e9,
//   category: "Interview Prep",
//   topics: ["Arrays", "Linked List", "Trees", "Graphs", "Dynamic Programming"],
//   duration: "20 hours",
//   level: "Beginner",
// ),
// Course(
//   id: "ip2",
//   title: "Coding Interview Problems",
//   description: "Practice real interview questions",
//   emoji: "💻",
//   studentCount: 21000,
//   color: 0xff0ea5e9,
//   category: "Interview Prep",
//   topics: ["LeetCode", "Patterns", "Optimization", "Edge Cases", "Practice"],
//   duration: "18 hours",
//   level: "Intermediate",
// ),
// Course(
//   id: "ip3",
//   title: "System Design Interview",
//   description: "Crack system design rounds",
//   emoji: "🏗️",
//   studentCount: 18500,
//   color: 0xff0ea5e9,
//   category: "Interview Prep",
//   topics: ["Scalability", "HLD", "LLD", "Case Studies", "Trade-offs"],
//   duration: "14 hours",
//   level: "Advanced",
// ),
// Course(
//   id: "ip4",
//   title: "Frontend Interview Prep",
//   description: "Prepare for frontend roles",
//   emoji: "🎨",
//   studentCount: 13200,
//   color: 0xff0ea5e9,
//   category: "Interview Prep",
//   topics: ["JavaScript", "React", "CSS", "Performance", "Questions"],
//   duration: "12 hours",
//   level: "Intermediate",
// ),
// Course(
//   id: "ip5",
//   title: "Backend Interview Prep",
//   description: "Prepare for backend roles",
//   emoji: "⚙️",
//   studentCount: 12400,
//   color: 0xff0ea5e9,
//   category: "Interview Prep",
//   topics: ["APIs", "DB Design", "Concurrency", "Caching", "Scalability"],
//   duration: "12 hours",
//   level: "Intermediate",
// ),
// Course(
//   id: "ip6",
//   title: "HR & Behavioral Interviews",
//   description: "Crack HR and soft skill rounds",
//   emoji: "🗣️",
//   studentCount: 9800,
//   color: 0xff0ea5e9,
//   category: "Interview Prep",
//   topics: ["HR Questions", "Communication", "Resume", "Confidence", "Negotiation"],
//   duration: "6 hours",
//   level: "Beginner",
// ),
];

List<String> getCategories() {
  final categories = allCourses.map((c) => c.category).toSet().toList();
  return ['All', ...categories];
}
